{% set version = '1.6.1' %}

package:
  name: dtc
  version: {{ version }}

source:
  fn: binutils-{{ version }}.tar.bz2
  url: https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-{{ version }}.tar.gz
  sha256: 6401c9a0f577a270df4632bf0f3e5454ccc7a5ca3caefa67a3e1c29c9c6b8c60

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}  [linux]
    - clang                [osx]
    - bison
    - flex
    - make
    - pkg-config
  host:
    # Python bindings
    - python {{ python }}
    - swig
  run:
    - python {{ python }}

test:
  imports:
    - libfdt
  commands:
    - dtc --help

about:
  home: https://git.kernel.org/pub/scm/utils/dtc/dtc.git
  license: GPL
  summary: 'Device Tree Compiler (dtc) toolchain for working with device tree source and binary files and also libfdt, a utility library for reading and manipulating the binary format.'
