name: Build packages

on:
  push:
  workflow_call:
    secrets:
      ANACONDA_TOKEN:
        description: 'Anaconda Token'
      ANACONDA_USER:
        description: 'Anaconda User'

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}

defaults:
  run:
    shell: bash

jobs:

  #8
  renode-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "renode"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #9
  renode-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "renode"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - run: brew install coreutils
      - uses: hdl/conda-eda/ci@master

  #10
  renode-windows:
    runs-on: "windows-2019"
    env:
      PACKAGE: "renode"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master
